# Generated by Django 4.1.5 on 2023-02-01 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement", models.CharField(max_length=200)),
                ("time", models.PositiveBigIntegerField(default=45000)),
                ("explaination", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "questions",
                    models.ManyToManyField(
                        help_text="Select questions for this quiz",
                        related_name="quizzes",
                        to="quizmaker.question",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "quizzes",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                help_text="Select a topic for this question",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="quizmaker.topic",
            ),
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("is_right", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Select a question for this option",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="quizmaker.question",
                    ),
                ),
            ],
        ),
    ]
