# Generated by Django 4.1.5 on 2023-02-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="description",
            field=models.TextField(default="Description"),
            preserve_default=False,
        ),
    ]
