# Generated by Django 4.1.5 on 2023-06-11 22:22

# Django Imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0003_answer_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="game",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizmaker.game",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="current_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_answers",
                to="quizmaker.answer",
            ),
        ),
    ]
