# Generated by Django 4.1.13 on 2023-11-12 23:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0005_gamequestion_alter_game_current_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="game",
            name="topic",
        ),
    ]
