# Generated by Django 4.1.13 on 2023-11-14 16:16

# Django Imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0006_remove_game_quiz_remove_game_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="text",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="question",
            name="statement",
            field=models.CharField(max_length=400),
        ),
    ]
