# Generated by Django 4.1.13 on 2023-11-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0007_alter_option_text_alter_question_statement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="statement",
            field=models.CharField(max_length=1250),
        ),
    ]
