# Generated by Django 4.1.13 on 2025-12-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizmaker", "0008_alter_question_statement"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="show_answer",
            field=models.BooleanField(default=False),
        ),
    ]
