# Generated by Django 4.1.13 on 2025-12-12 21:25

import apps.quizmaker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizmaker", "0009_game_show_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.quizmaker.models.generate_image_path
            ),
        ),
    ]
