services:
  app:
    build:
      context: .
      dockerfile: ./compose/development/app/Dockerfile
    image: halfquiz_development_app
    stdin_open: true
    tty: true
    command: bash
    labels:
      name: halfquiz_app
    ports:
      - 8000:8000
    environment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - MINIMUM_PASSING_PERCENTAGE=${MINIMUM_PASSING_PERCENTAGE}
      - DEFAULT_NUMBER_OF_QUESTIONS=${DEFAULT_NUMBER_OF_QUESTIONS}
    volumes:
      - ./:/app
