user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  512;
    multi_accept off;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr [$time_local] "$request" $status $body_bytes_sent';
    access_log  /var/log/nginx/access.log main;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;

    keepalive_timeout  15;
    keepalive_requests 100;

    client_max_body_size 100M;

    server_tokens off;

    client_body_buffer_size 16k;
    client_header_buffer_size 1k;
    large_client_header_buffers 2 8k;

    proxy_buffering on;
    proxy_buffers 4 16k;
    proxy_buffer_size 8k;

    # Avoid resolving DNS repeatly on Docker
    resolver 127.0.0.11 valid=30s ipv6=off;

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl http2;
        listen [::]:443 ssl;
        server_name halfquiz.xtrem.sh;
        charset utf-8;

        ssl_certificate     /etc/nginx/ssl/halfquiz.cert.pem;
        ssl_certificate_key /etc/nginx/ssl/halfquiz.key.pem;

        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        add_header Strict-Transport-Security "max-age=31536000" always;
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options DENY;
        add_header X-XSS-Protection "1; mode=block";

        location /static/ {
            alias /app/staticfiles/;
            access_log off;
            expires 30d;
            add_header Cache-Control "public";
        }

        location /media/ {
            alias /app/media/;
            access_log off;
            expires 7d;
        }

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-For $remote_addr;

            proxy_connect_timeout 5s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;

            proxy_http_version 1.1;
            proxy_set_header Connection "";

            proxy_pass http://app:8000;
        }
    }
}
